### ISSUE TITLE
Results not fully rendering.

### ISSUE THREAD

**Issue by just-smol** [DLMSweet/MDRSS#5] opened 2024-01-31 19:59 UTC
I'm not sure if this is an issue only with Pagination or in general. But the results per page do not match the number listed. Multiple can be missing and it varies from page to page. One series I am searching for does not return its exact name, possibly because its missing from the list. It's possible the array is clipped or corrupted.
![image](https://github.com/DLMSweet/MDRSS/assets/44164901/68d1fe47-75b5-416c-af2b-d1c2683c0043)
![image](https://github.com/DLMSweet/MDRSS/assets/44164901/8c11400c-1f4e-4588-9ffc-040483fc0127)
![image](https://github.com/DLMSweet/MDRSS/assets/44164901/513d79ff-293e-4b1d-8517-e9ecb8d21d26)

**Comment by DLMSweet** [comment] 2024-01-31 20:35
Should be fixed, please try now. Dumb coding decisions I made.

**Comment by just-smol** [comment] 2024-02-02 14:44
It works on all result pages except the first page now. Which still seems to clip 1 result.
![image](https://github.com/DLMSweet/MDRSS/assets/44164901/79fbb219-eff6-4ba7-ad0a-2172c43dab83)
![image](https://github.com/DLMSweet/MDRSS/assets/44164901/4efacae2-8b01-4399-9a92-aa0273f88ecc)

**Comment by DLMSweet** [comment] 2024-02-03 01:26
So, dumb mistakes, my failback didn't actually failback - it just failed. So NOW, this is probably working as intended. Let me know if you find any other cases where it fails to display all the results.

**Closed as completed** 2024-02-05 14:02 UTC
